// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add-pacient": {
            "post": {
                "description": "Cria um toke para auth do usuario",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pacient"
                ],
                "summary": "Criar token de auth",
                "parameters": [
                    {
                        "description": "Dados do Doutor a ser criado",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pInter.InputPacient"
                        }
                    },
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Token de autenticação (Colocar o token deixando o Bearer)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token make:",
                        "schema": {
                            "$ref": "#/definitions/pInter.Pacient"
                        }
                    }
                }
            }
        },
        "/add-questions": {
            "post": {
                "description": "Um novo metodo de adicionar as questoes no back",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Adicionar as questoes",
                "parameters": [
                    {
                        "description": "Dados do Doutor a ser criado",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inter.Resp"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Doutor criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/inter.OutputDoctor"
                        }
                    }
                }
            }
        },
        "/api/create-doctor": {
            "post": {
                "description": "Cria um novo Doutor no banco de dados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Doctor"
                ],
                "summary": "Cria um novo Doutor",
                "parameters": [
                    {
                        "description": "Dados do Doutor a ser criado",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inter.ControllerDoctor"
                        }
                    },
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Token de autenticação (Colocar o token deixando o Bearer)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Doutor criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/inter.OutputDoctor"
                        }
                    },
                    "406": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/erros.NotAcceptable"
                        }
                    }
                }
            }
        },
        "/api/modify-doctor": {
            "put": {
                "description": "Altera o doutor, tem que me passar oque precisa alterar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Doctor"
                ],
                "summary": "Altera Doutor",
                "parameters": [
                    {
                        "description": "Dados do Doutor a ser criado",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inter.ControllerDoctor"
                        }
                    },
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Token de autenticação (Colocar o token deixando o Bearer)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Doutor criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/inter.OutputDoctor"
                        }
                    }
                }
            }
        },
        "/api/pull-questions": {
            "get": {
                "responses": {}
            }
        },
        "/api/search-doctor": {
            "get": {
                "description": "Buscar um novo Doutor no banco de dados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Doctor"
                ],
                "summary": "Buscar um doutor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email do doutor",
                        "name": "Email",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Token de autenticação (Colocar o token deixando o Bearer)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Doutor criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/inter.OutputDoctor"
                        }
                    }
                }
            }
        },
        "/api/test-token": {
            "post": {
                "description": "Cria um toke para auth do usuario",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Test Token",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Token de autenticação",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token make:",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/token": {
            "get": {
                "description": "Cria um toke para auth do usuario",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Criar token de auth",
                "responses": {
                    "200": {
                        "description": "token make:",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "base.LogData": {
            "type": "object",
            "properties": {
                "ExecutionTime": {
                    "type": "string"
                },
                "HttpStatusCode": {
                    "type": "integer"
                },
                "IP": {
                    "type": "string"
                },
                "Route": {
                    "type": "string"
                }
            }
        },
        "erros.Message": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "erros.NotAcceptable": {
            "type": "object",
            "properties": {
                "LogData": {
                    "$ref": "#/definitions/base.LogData"
                },
                "NotAcceptable": {
                    "$ref": "#/definitions/erros.Message"
                }
            }
        },
        "inter.ControllerDoctor": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "zipCode": {
                    "type": "string"
                }
            }
        },
        "inter.OutputDoctor": {
            "type": "object",
            "properties": {
                "Login_idLogin": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "create_at": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "update_at": {
                    "type": "string"
                },
                "zipCode": {
                    "type": "string"
                }
            }
        },
        "inter.Question": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                }
            }
        },
        "inter.Resp": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "$ref": "#/definitions/inter.Question"
                }
            }
        },
        "pInter.Brothers": {
            "type": "object",
            "properties": {
                "health": {
                    "type": "string"
                },
                "neuroDivergent": {
                    "type": "string"
                }
            }
        },
        "pInter.Family": {
            "type": "object",
            "properties": {
                "brothers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pInter.Brothers"
                    }
                },
                "parents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pInter.Parents"
                    }
                }
            }
        },
        "pInter.InputPacient": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "family": {
                    "$ref": "#/definitions/pInter.Family"
                },
                "gender": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "neuroDivergent": {
                    "type": "string"
                },
                "pdfContent": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "phone": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "pInter.Pacient": {
            "type": "object",
            "properties": {
                "Doctor_idDoctor": {
                    "type": "integer"
                },
                "Family_idFamily": {
                    "type": "integer"
                },
                "Login_idLogin": {
                    "type": "integer"
                },
                "Skills_idSkills": {
                    "type": "integer"
                },
                "age": {
                    "type": "integer"
                },
                "create_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "neuroDivergent": {
                    "type": "string"
                },
                "pdfContent": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "phone": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "update_at": {
                    "type": "string"
                }
            }
        },
        "pInter.Parents": {
            "type": "object",
            "properties": {
                "neuroDivergent": {
                    "type": "string"
                },
                "relationShip": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Milie Mind",
	Description:      "This is a server for app.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
